### ISSUE TITLE
1- Login Page

### ISSUE THREAD

**Issue by jinwu23** [hack4impact-calpoly/general-volunteer-management-system#1]
**Description**
Create Login Page

**Acceptance Criteria**
Code is clean and properly formatted
Component reflects Figma design 

Steps:
- Create a new page under src/app/pages/authentication/login named page.tsx
- Ensure that component matches [Figma ](https://www.figma.com/file/Mv4wKS0WTiszMuiDbLcpTi/General-VMS-Figma?type=design&node-id=0%3A1&mode=design&t=70bklaMYPbGHtiJN-1)  (Log in - Desktop)
- Ensure form validation for Email and Password (ex - valid email, password is not blank) 
- Create Account links to create account page even if it does not exist yet 

**Additional Information**
![image](https://github.com/hack4impact-calpoly/general-volunteer-management-system/assets/69867265/08c9062a-1ea7-4d64-93e9-c74d702a7884)

**Comment by HubertGrabda** [comment]
Hi!
I can help with that : )

**Comment by HubertGrabda** [comment]
Hey, tommrow I will post a PR on this issue ;)
